version: '3'
services:
        revproxy:
                image: jwilder/nginx-proxy
                environment:
                        - DEFAULT_HOST=sid
                volumes:
                        - /var/run/docker.sock:/tmp/docker.sock
                ports:
                        - 80:80
        web:
                image: katacoda/docker-http-server:latest
                environment: 
                        - VIRTUAL_HOST=sid
#COMMAND:  docker-compose up -d --scale web=5
#docker container run -d --network net -p 80:80 -e DEFAULT_HOST=sid -v /var/run/docker.sock:/tmp/docker.sock jwilder/nginx-proxy
#docker container run -d -p 80 --network net -e VIRTUAL_HOST=sid gitfile
# "gitfile is my custom website"
# The reverse proxy should have an environment variable set as DEFAULT_HOST and all proxied container VIRTUAL_HOST.
